### Below is a concise yet friendly explanation of the attention mechanism for assignment introduction:

#### Attention Mechanism (Adapted from “Attention Is All You Need”)

The attention mechanism, introduced in Attention Is All You Need (Vaswani et al., 2017), processes inputs represented as vectors (each row is a token embedding of dimension $𝐷$). We compute three sets of vectors: queries (Q), keys (K), and values (V). The core steps are:

1. **Linear Transformations:**  

Let $X$ be the input matrix, where each of the rows corresponds to a token in the input sequence, and each row is a $d$-dimensional embedding vector.

To compute attention, we first project $X$ into three different representations using learned weight matrices:

Each input vector is transformed into $Q$, $K$, and $V$ using learnable weights.

$$
\begin{aligned}
Q_i &= X W_i^Q, \\
K_i &= X W_i^K, \\
V_i &= X W_i^V.
\end{aligned}
$$

Each head \(i\) has its own learnable parameters $W_i^Q$, $W_i^K$, and $W_i^V$, which transform the input into queries, keys, and values, respectively.


2. **Scaled Dot-Product Attention:**  

\begin{equation}
\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^\top}{\sqrt{d_k}}\right)V.
\end{equation}

Here, $QK^T$ produces a matrix of scores that measures how relevant each “query” position is to every “key” position. $d_k$ is the dimension of queries and keys. 

The softmax function converts these scores into attention weights (non-negative values that sum to 1 across each row).

These weights are then used to combine the values 𝑉 to produce the final output.




3. **Multi-Head Attention:**  

$$
\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \dots, \text{head}_h)
$$

$$
\text{where } \text{head}_i = \text{Attention}(QW_i^Q, KW_i^K, VW_i^V).
$$


Multiple attention heads allow the model to attend to different aspects of the input simultaneously. For each of these heads we use $d_k = d_{model}/H$. Their outputs are concatenated and linearly transformed to produce the final result.



*Note:* In this assignment, you are only required to experiment with the provided $Q$, $K$, and $V$ matrices to perform the matrix multiplication

## Self-attention Computer Assignment 


Implement the multi-head self-attention operation, taking in a set of $N$ vectors of $D$ dimensions and outputting a matrix of the same size. Do this without relying on neural network libraries, but rather write directly the required operations in NumPy. 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Data size
N = 5
D = 6

X = [[ 0.7, -0.8, -1.2,  -1.,  -0., -0.3],
     [ 2.7,  0.1,  1.6,  1.8,  1.5,  0.3],
     [ 0.1,  2.6, -0.1, -1.3, -0.5, -0.7],
     [ 1.1,  1.5,   1., -0.5,  0.4,  0.4],
     [-0.7, -0.7,  0.7, -1.5, -0.8,  1. ]]

Wq = [[-1.7,  1.6,  0.9, -0.5,  0.4,  -1.],
      [-0.4,  1. , -0.3,  1. ,  0.5,  1.1],
      [ 0.4, -0.9,  -1.,  0.5, -1.4,  0. ],
      [ 0.3,  1.4, -1.2,  0.2,  0.1,  1.6],
      [-0.8,  0.8, -0.7, -1.3,  0.3,  0.8],
      [ 1.1,  0.3, -1.5, -2.3,  2.2, -0.7]]

Wk = [[ 0.3, -0.4, -1.3,  0.3, -1.7,  1.1],
      [-2.3, -1.1,  0.6, -1.2,  2.2,  0.3],
      [ 1.1, -0.4, -0.5,  1.9, -1.1, -1.2],
      [-0.4,  1. , -1.7,  0. , -3.3, -1.4],
      [-0.9, -1.1, -1. ,  1.4,  1.3,  1.2],
      [-0.7,  0.4,  0.4, -1.4, -0.2, -0.5]]

Wv = [[-0.1,  0.7,  1. , -0.1,  1.6,  0.9],
      [ 0.4, -1. , -0.7, -0.6, -0.9, -0.1],
      [-0.4,  0.5, -1.4,  0.1,  0.6,  0.4],
      [ 1.4, -1.3, -1.3, -0.6,  1.6, -0.2],
      [-0.4, -0.6, -1.4, -1. ,  0.4, -0.8],
      [ 0.2,  0.5,  0.4, -0.5,  1.4,  2.3]]



X = np.array(X)
Wq = np.array(Wq)
Wk = np.array(Wk)
Wv = np.array(Wv)

### (a) Implement the self-attention operation

In [3]:
def self_attention(X, Wq, Wk, Wv):
	...
	query = X.dot(Wq)
	key = X.dot(Wk)
	value = X.dot(Wv)
	
	d_k = key.shape[1]
	scores = query.dot(key.T) / (d_k ** 0.5)
	attention_weights = np.exp(scores) / np.sum(np.exp(scores), axis = -1, keepdims = True)
	output = attention_weights.dot(value)
	return output, attention_weights


In [4]:
# Compute the output
output, attention_weights = self_attention(X, Wq, Wk, Wv)

# Print in a nice format
np.set_printoptions(precision=1)
print("Self-Attention Output:\n", output)
print("Self-Attention Matrix:\n", attention_weights)

Self-Attention Output:
 [[-0.7 -0.9  0.5  0.1 -5.5 -1.1]
 [-0.4  0.6  0.6 -0.6  2.   0.5]
 [ 0.3 -0.1 -2.4 -1.9  4.9  1.8]
 [-0.7 -0.7  0.4 -0.1 -4.5 -0.7]
 [-2.   3.3  2.1  1.6 -1.3  2.8]]
Self-Attention Matrix:
 [[4.9e-07 4.0e-14 9.9e-01 1.7e-05 6.1e-03]
 [4.8e-01 3.6e-01 1.5e-01 2.1e-02 4.0e-04]
 [1.9e-02 5.8e-01 9.4e-02 2.8e-01 3.2e-02]
 [3.0e-02 1.2e-02 8.5e-01 9.9e-02 1.1e-02]
 [4.7e-04 7.3e-03 1.6e-02 4.0e-02 9.4e-01]]


### (b) Implement multi-head attention, using the previously implemented function

In [5]:
def multi_head_attention(X, Wq, Wk, Wv, H):
	...
	head_dim = Wq.shape[1] // H
	outputs = []
	attention_weights = []
	
	for h in range(H):
		start = h * head_dim
		end = (h+1) * head_dim

		# split by row for each head
		Wq_h = Wq[:, start:end]	
		Wk_h = Wk[:, start:end]
		Wv_h = Wv[:, start:end]

		output_h, attention_weights_h = self_attention(X, Wq_h, Wk_h, Wv_h)

		outputs.append(output_h)
		attention_weights.append(attention_weights_h)

	output = np.hstack(outputs)
	attention_weights = np.array(attention_weights)
	return output, attention_weights


In [6]:
# Compute multi-head attention
H = [1, 3]
for head_number in H:
	output, attention_weights = multi_head_attention(X, Wq, Wk, Wv, head_number)
	print(f"head number: {head_number}, multi head attention output:\n {output}")
	print(f"head number: {head_number}, multi head attention weights:\n {attention_weights}")

head number: 1, multi head attention output:
 [[-0.7 -0.9  0.5  0.1 -5.5 -1.1]
 [-0.4  0.6  0.6 -0.6  2.   0.5]
 [ 0.3 -0.1 -2.4 -1.9  4.9  1.8]
 [-0.7 -0.7  0.4 -0.1 -4.5 -0.7]
 [-2.   3.3  2.1  1.6 -1.3  2.8]]
head number: 1, multi head attention weights:
 [[[4.9e-07 4.0e-14 9.9e-01 1.7e-05 6.1e-03]
  [4.8e-01 3.6e-01 1.5e-01 2.1e-02 4.0e-04]
  [1.9e-02 5.8e-01 9.4e-02 2.8e-01 3.2e-02]
  [3.0e-02 1.2e-02 8.5e-01 9.9e-02 1.1e-02]
  [4.7e-04 7.3e-03 1.6e-02 4.0e-02 9.4e-01]]]
head number: 3, multi head attention output:
 [[-0.7 -0.9  0.7  0.2 -1.5  2.9]
 [-1.1  0.9 -3.9 -2.9 -3.  -0.5]
 [-0.7 -0.9  1.6  1.2  5.8  1.5]
 [-0.7 -0.7 -3.8 -2.8 -5.1 -0.9]
 [-0.2  0.3  1.   0.2 -1.3  3. ]]
head number: 3, multi head attention weights:
 [[[1.8e-04 1.2e-03 9.5e-01 4.6e-02 2.3e-05]
  [5.1e-01 1.7e-02 3.6e-01 1.0e-02 1.0e-01]
  [6.4e-04 2.5e-03 9.4e-01 5.4e-02 9.7e-05]
  [3.8e-02 2.6e-02 8.4e-01 8.8e-02 1.0e-02]
  [2.6e-02 3.2e-01 4.5e-02 5.3e-01 7.7e-02]]

 [[3.1e-05 2.0e-18 9.0e-01 4.8e-07 9.7

### (c+d) Provide the answers/explanations requested in the problem sheet:
1. Why the results are different?
2. What happens if you change the order of two inputs=

In [7]:
X_reordered = np.array([
    [ 2.7,  0.1,  1.6,  1.8,  1.5,  0.3],
	[ 0.7, -0.8, -1.2,  -1.,  -0., -0.3],
    [ 0.1,  2.6, -0.1, -1.3, -0.5, -0.7],
    [ 1.1,  1.5,   1., -0.5,  0.4,  0.4],
    [-0.7, -0.7,  0.7, -1.5, -0.8,  1. ]
])

# Compute multi-head attention
H = [1, 3]
for head_number in H:
	output_reordered, attention_weights_reordered = multi_head_attention(X_reordered, Wq, Wk, Wv, head_number)
	output, attention_weights = multi_head_attention(X, Wq, Wk, Wv, head_number)
	print(f"head number: {head_number}, multi head attention output:\n {output}")
	print(f"head number: {head_number}, multi head attention output reordered:\n {output_reordered}")
	print(f"head number: {head_number}, multi head attention weights:\n {attention_weights}")
	print(f"head number: {head_number}, multi head attention weights reordered:\n {attention_weights_reordered}")


head number: 1, multi head attention output:
 [[-0.7 -0.9  0.5  0.1 -5.5 -1.1]
 [-0.4  0.6  0.6 -0.6  2.   0.5]
 [ 0.3 -0.1 -2.4 -1.9  4.9  1.8]
 [-0.7 -0.7  0.4 -0.1 -4.5 -0.7]
 [-2.   3.3  2.1  1.6 -1.3  2.8]]
head number: 1, multi head attention output reordered:
 [[-0.4  0.6  0.6 -0.6  2.   0.5]
 [-0.7 -0.9  0.5  0.1 -5.5 -1.1]
 [ 0.3 -0.1 -2.4 -1.9  4.9  1.8]
 [-0.7 -0.7  0.4 -0.1 -4.5 -0.7]
 [-2.   3.3  2.1  1.6 -1.3  2.8]]
head number: 1, multi head attention weights:
 [[[4.9e-07 4.0e-14 9.9e-01 1.7e-05 6.1e-03]
  [4.8e-01 3.6e-01 1.5e-01 2.1e-02 4.0e-04]
  [1.9e-02 5.8e-01 9.4e-02 2.8e-01 3.2e-02]
  [3.0e-02 1.2e-02 8.5e-01 9.9e-02 1.1e-02]
  [4.7e-04 7.3e-03 1.6e-02 4.0e-02 9.4e-01]]]
head number: 1, multi head attention weights reordered:
 [[[3.6e-01 4.8e-01 1.5e-01 2.1e-02 4.0e-04]
  [4.0e-14 4.9e-07 9.9e-01 1.7e-05 6.1e-03]
  [5.8e-01 1.9e-02 9.4e-02 2.8e-01 3.2e-02]
  [1.2e-02 3.0e-02 8.5e-01 9.9e-02 1.1e-02]
  [7.3e-03 4.7e-04 1.6e-02 4.0e-02 9.4e-01]]]
head number: 3, mu

### Answers

1. When using the multi head method we split the weight matrices into smaller matrices with same number of columns for each head but we process the same input resulting into a mechanims that allows different heads to attend to different parts of the input. Even though we use the same matrices in the multi head implementation each head is allowed to use only a certain partition of each matrix $$\begin{aligned} Q_i &= X W_i^Q, \\ K_i &= X W_i^K, \\ V_i &= X W_i^V. \end{aligned} $$ resulting in each head projecting into an **independent 2D subspace** and computing the attention separately in each. Finally each individual output is concatenated to form the final result $$\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \dots, \text{head}_h)$$ This process is very different from the single head implementation where one single head can attend the full input with the full dimentionality of the weight matrices. In conclusion there is no single operation that allows us to pinpoint where the two results break apart but we can say with certainty that the two results differ because of compound effect of:	1. lower dimensional projections	2. separate attention weight matrices	3. independent softmax operations	4. concatenation of final head outputs. We can say with certainty that the more expressive model is the multi head method because each head can extract different information from the input compared to only one head (eg. instead of only one perspective about the input, each head computes a different perspective equally weighted in the final output).
2. When changing the order of the first two inputs we can notice that for the single head implementation the final output is the same, although the weights matrices are different. This happens because we are only relying on one attention head and the operations inside one single head would simply permutate the outputs in the same order as the rearrangement of the input (eg. $X' = \begin{bmatrix} x_1 \\ x_0 \\ x_2 \\ x_3 \\ x_4 \\ \end{bmatrix}$ would give us $Q' = \begin{bmatrix} q_1 \\ q_0 \\ q_2 \\ q_3 \\ q_4 \\ \end{bmatrix}$, this process is extended to the final output $Output' = P \cdot Output$ where P is a permutation matrix that rearranges the rows). On the other hand in the multi head implementation we see that the output is different from the original multi head output, this happens because we are now relying on multiple heads that compute their own attention matrices for different parts of the input and compute a final output that is the concatenation of the single outputs. Since the result is a concatenation of different feature projections reordering the input results in a different mix of subspace outputs making the final result not just a permutation but a totally different output.